### ISSUE TITLE
Make sure the frontend sends API requests to its own server by default

### ISSUE THREAD

**Issue by bonndan** [dedica-team/nivio#203]
As observed in https://github.com/dedica-team/nivio/issues/179 the frontend sends requests to heroku after having build and run the jar/docker image.

- [x] make sure the frontend sends API requests to localhost:8080 by default, if not overriden
- [x] provide a way to override the API url and document it

**Comment by MarvinSchoening** [comment]
well there is already a way to override/change the api url :D .env file, i just have to add a reminder into the readme. its on default localhost:8080 on development  and what ever you set in .env (currently heroku to make deployment a bit easier) for production

**Comment by MarvinSchoening** [comment]
seems like the problem lies within our pom.xml. if you only start the nivio backend, it will also start the frontend on localhost:8080 and use the production build (and therefore not .env.development, but always .env). this is intended for production builds and for heroku but doesnt work for local development. for local development its crucial to start the frontend on your own and use localhost:3000. i dont know yet if there's a way to tell the pom.xml to start in development mode if needed because yarn build always sets node_env to production (https://create-react-app.dev/docs/adding-custom-environment-variables) and yarn dev wont create a build folder that can be copied into our backend target folder. i guess we should just update the readme and give proper instructions for local development and make clear that you have to change your .env to your own URL

**Comment by MarvinSchoening** [comment]
but i dont recommend to develop the frontend local via docker or jar because you have to rebuild it everytime after changes and lose the hot reload feature because of that
