### ISSUE TITLE
Define YOUR major usecase, collect selling points

### ISSUE THREAD

**Issue by bonndan** [dedica-team/nivio#795]
Pick the usecase that is most important in your opinion in order to have a starting point for further action.

See https://medium.dave-bailey.com/how-to-perfectly-capture-your-customers-need-c924e3209484

```
For ___[target audience], it’s a constant challenge to ___[general problem]. Every ___[time period], these people ___[perform a key activity] in order to ___[achieve a primary goal]. This is especially true if you’re a [niche].
The main problem they face is ___[primary functional problem relating to activity] which leads to ___[bad/worst case outcomes]. Today, their best option is ___[substitutes], but of course, they ___[the most common complaints of each substitute]. With ___[key trend], the problem will only get worse over time.
```

### Fill the spaces:

-  @robrobert99 
-  @jenarp 
- @bonndan 

> For development teams, it’s a constant challenge to keep track of changes and status in multi-service landscapes. Every day, these people have to fix bugs and implement new features in order to deliver business value. This is especially true if you’re a microservice environment.
> The main problem they face is insufficient knowledge which leads to unfitting or redundant implementations. Today, their best option is use static documentation and frequent meetings, but of course, the documentation is hardly maintained and often outdated. With microservices and ever growing systems, the problem will only get worse over time.

- [ ] pick one major usecase for the landingpage draft https://github.com/dedica-team/nivio-landingpage
- [ ] review landingpage draft

**Comment by jenarp** [comment]
For project managers and in the end also for the the managing directors of medium-sized companies, it’s a constant challenge to evaluate the environmental and ethical aspects of the supply and production chains of each project/company.

After each projects’ completion, the project managers draw the balance in order to gain insight about costs/profit, possible delays, clients satisfaction, etc.. 
The main problem they face is that they have no time and also no idea about how to start to evaluate ethical aspects which leads to frustration. 
Today, their best option is to evaluate a hand-made excel file, but of course, this takes a lot of time, has plenty of uncertainties and uses bad/false estimates. With the increase of the work load (number of projects to manage) and the complexity of each project (more and new suppliers, more complex technology, …), the problem will only get worse over time.
