### ISSUE TITLE
Unsatisfying behaviour after log out

### ISSUE THREAD

**Issue by jenarp** [dedica-team/nivio#900]
**Describe the bug**
nivio Environment variable: "NIVIO_AUTH_LOGIN_MODE=required":
When logging out with button on localhost:3000:
- localhost:8080/user still gives information of logged in user. 
- Access to demo landscape still given

Is this expected behaviour?

**To Reproduce**
1. Run app with NIVIO_AUTH_LOGIN_MODE=required
2. login via localhost:8080
3. Go to localhost:3000 and click logout button
4. Go to localhost:8080/user -> see that user information is still available
5. Go back to localhost:3000 -> still access to all landscapes

**Expected behavior**
After logout: 
- no user information at localhost:8080/user
- no possibility to enter demo landscapes

**Screenshots after logout**
<img width="1723" alt="Screenshot 2022-05-02 at 12 28 22" src="https://user-images.githubusercontent.com/67540243/166221497-6d5a1839-a21b-4c0b-9ff0-45262067ed55.png">
![Screenshot 2022-05-02 at 10 20 58](https://user-images.githubusercontent.com/67540243/166221526-25055a48-ff1a-4198-9c0b-0b52ca7a5ff8.png)
<img width="1272" alt="Screenshot 2022-05-02 at 12 36 31" src="https://user-images.githubusercontent.com/67540243/166221537-a2da4aa5-9607-41a7-9e28-bb0dca4a71eb.png">

**Comment by bonndan** [comment]
@jenarp This most likely is a misunderstanding: we route to /logout in order to exit, but in development mode on port 3000 /logout is answered by the node js server which does not have logout functionality. 

We could however provide the frontend with a complete link to the backend logout address (e.g. on port 8080), then the logout would work in development. In production, behind proxies etc., we face new challenges then, however. So my advice is to close this issue.
